mysql:
  dataBase: lock_db
  userName: root
  passWord: rootroot
  port: 3306
  driverName: mysql
  host: 127.0.0.1
  log_Level: dev
logger:
  level: info
  prefix: '[Lock]'
  director: log
  show-line: true
  log-in-console: true
system:
  host: 0.0.0.0
  post: 8080
  env: release
site_info:
  created_at: "2026-02-28"
  title: Smart_delivery_locker
  email: zxd2839182980@163.com
  name: Roy
jwt:
  secret: Roy
  expires: 48
  issuer: Lock
upload:
  size: 5
  size_avatar: 2
  path: uploads/file
  path_avatar: uploads/avatar
redis:
  ip: 127.0.0.1
  port: 6379
  password: redis
  pool_size: 100
admin:
  username: Roy
  avatar: uploads/avatar/Roy.png
  github: ""
  bilibili: ""
